export const demoTiles = [
    {
        id: 2,
        name: "Bomba",
        pcs: 6,
        icon: "bomb",
        i_id: "b",
    },
    {
        id: 3,
        name: "Tábornagy",
        level: 10,
        pcs: 1,
        i_id: 10,
    },
    {
        id: 4,
        name: "Tábornok",
        level: 9,
        pcs: 1,
        i_id: 9,
    },
    {
        id: 5,
        name: "Ezredes",
        level: 8,
        pcs: 2,
        i_id: 8,
    },
    {
        id: 6,
        name: "Őrnagy",
        level: 7,
        pcs: 3,
        i_id: 7,
    }
]

export const demoEnemyTiles = [
    {
        id: 2,
        name: "Bomba",
        pcs: 6,
        icon: "bomb",
        i_id: "b",
    },
    {
        id: 3,
        name: "Tábornagy",
        level: 10,
        pcs: 1,
        i_id: 10,
    },
    {
        id: 4,
        name: "Tábornok",
        level: 9,
        pcs: 1,
        i_id: 9,
    },
    {
        id: 5,
        name: "Ezredes",
        level: 8,
        pcs: 2,
        i_id: 8,
    },
    {
        id: 6,
        name: "Őrnagy",
        level: 7,
        pcs: 3,
        i_id: 7,
    },
    {
        id: 2,
        name: "Bomba",
        pcs: 6,
        icon: "bomb",
        i_id: "b",
    },
    {
        id: 3,
        name: "Tábornagy",
        level: 10,
        pcs: 1,
        i_id: 10,
    },
    {
        id: 4,
        name: "Tábornok",
        level: 9,
        pcs: 1,
        i_id: 9,
    },
    {
        id: 5,
        name: "Ezredes",
        level: 8,
        pcs: 2,
        i_id: 8,
    },
    {
        id: 6,
        name: "Őrnagy",
        level: 7,
        pcs: 3,
        i_id: 7,
    },
    {
        id: 2,
        name: "Bomba",
        pcs: 6,
        icon: "bomb",
        i_id: "b",
    },
    {
        id: 3,
        name: "Tábornagy",
        level: 10,
        pcs: 1,
        i_id: 10,
    },
    {
        id: 4,
        name: "Tábornok",
        level: 9,
        pcs: 1,
        i_id: 9,
    },
    {
        id: 5,
        name: "Ezredes",
        level: 8,
        pcs: 2,
        i_id: 8,
    },
    {
        id: 6,
        name: "Őrnagy",
        level: 7,
        pcs: 3,
        i_id: 7,
    }
]