export const tiles = [
    {
        id: 1,
        name: "Zászló",
        pcs: 1,
        icon: "flag",
        i_id: "f",
    },
    {
        id: 2,
        name: "Bomba",
        pcs: 6,
        icon: "bomb",
        i_id: "b",
    },
    {
        id: 3,
        name: "Tábornagy",
        level: 10,
        pcs: 1,
        i_id: 10,
    },
    {
        id: 4,
        name: "Tábornok",
        level: 9,
        pcs: 1,
        i_id: 9,
    },
    {
        id: 5,
        name: "Ezredes",
        level: 8,
        pcs: 2,
        i_id: 8,
    },
    {
        id: 6,
        name: "Őrnagy",
        level: 7,
        pcs: 3,
        i_id: 7,
    },
    {
        id: 7,
        name: "Kapitány",
        level: 6,
        pcs: 4,
        i_id: 6,
    },
    {
        id: 8,
        name: "Főhadnagy",
        level: 5,
        pcs: 4,
        i_id: 5,
    },
    {
        id: 9,
        name: "Őrmester",
        level: 4,
        pcs: 4,
        i_id: 4,
    },
    {
        id: 10,
        name: "Aknász",
        level: 3,
        pcs: 5,
        i_id: 3,
    },
    {
        id: 11,
        name: "Felderítő",
        level: 2,
        pcs: 8,
        i_id: 2,
    },
    {
        id: 12,
        name: "Kém",
        level: 1,
        pcs: 1,
        i_id: 1,
    },
]